### ISSUE TITLE
新的权限错误

### ISSUE THREAD

**Issue by yuangezhizao** [faceair/youjumpijump#24]
```
shell@mx4pro:/ $ cd /data/local/tmp/ && chmod 775 ./youjumpijump && ./youjumpijump
/local/tmp/ && chmod 775 ./youjumpijump && ./youjumpijump                     <
input jump ratio (recommend 2.04):2.04
2.04
2017/12/31 06:30:10 now jump ratio is 2.040000
2017/12/31 06:30:16 from:[224 694] to:[526 525] press:705ms
panic: open /data/local/tmp/debugger/: permission denied
        panic: open /data/local/tmp/debugger/: permission denied

goroutine 1 [running]:
main.debugger()
        /Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:76 +0x278
main.main.func1()
        /Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:94 +0x14
panic(0x105d70, 0x108b0080)
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x204
main.debugger()
        /Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:76 +0x278
main.main()
        /Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:112 +0xd28
```

**Comment by faceair** [comment]
很奇怪.. 为啥没有这个目录的权限..

**Comment by yuangezhizao** [comment]
上一个` cd /data/local/tmp/ && chmod 775 ./youjumpijump && ./youjumpijump`，
刚试了这个`cd /data/local/tmp/ && chmod 775 ./youjumpijump || true && ./youjumpijump`也没有权限……
```
shell@mx4pro:/data/local/tmp $ cd /data/local/tmp/ && chmod 775 ./youjumpijump || true && ./youjumpijump
d /data/local/tmp/ && chmod 775 ./youjumpijump || true && ./youjumpijump      <
input jump ratio (recommend 2.04):2.04
2.04
2017/12/31 06:46:25 now jump ratio is 2.040000
panic: open /data/local/tmp/debugger/: permission denied
        panic: open /data/local/tmp/debugger/: permission denied

goroutine 1 [running]:
main.debugger()
        /Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:76 +0x278
main.main.func1()
        /Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:94 +0x14
panic(0x105d70, 0x11c4a240)
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x204
main.debugger()
        /Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:76 +0x278
main.main()
        /Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:112 +0xd28
```

**Comment by Hn1993** [comment]
我也遇到这个错误  你进入shell目录 找到youjumpijump  chmod 777 youjumpijump
 然后./youjumpijump  
就可以了

**Comment by yuangezhizao** [comment]
@Hn1993 
我这里还是不行，
```
shell@mx4pro:/data/local/tmp $ chmod 777 youjumpijump
chmod 777 youjumpijump
shell@mx4pro:/data/local/tmp $ ./youjumpijump
./youjumpijump
input jump ratio (recommend 2.04):2.04
2017/12/31 06:52:57 now jump ratio is 2.040000
panic: open /data/local/tmp/debugger/: permission denied
        panic: open /data/local/tmp/debugger/: permission denied

goroutine 1 [running]:
main.debugger()
        /Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:76 +0x278
main.main.func1()
        /Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:94 +0x14
panic(0x105d70, 0x10c88080)
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x204
main.debugger()
        /Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:76 +0x278
main.main()
        /Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/main.go:112 +0xd28
```

**Comment by faceair** [comment]
`cd /data/local/tmp/ && mkdir debugger` 手动建个目录看看

**Comment by yuangezhizao** [comment]
```
shell@mx4pro:/data/local/tmp $ chmod 777 /data/local/tmp/debugger
chmod 777 /data/local/tmp/debugger
Unable to chmod /data/local/tmp/debugger: Operation not permitted
10|shell@mx4pro:/data/local/tmp $ ls -l
ls -l
drwxr-x--- root     root              2017-12-31 14:29 debugger
-rw------- root     root        85612 2017-12-31 14:29 jump.720.png
-rw-rw-r-- shell    shell       94567 2017-12-31 14:30 jump.png
-rwxrwxrwx shell    shell     2662585 2017-12-31 13:26 youjumpijump
```

**Comment by Hn1993** [comment]
先去看看/data/local/tmp/  有没有youjumpijump这个文件  我用的是模拟器

**Comment by yuangezhizao** [comment]
手动在真机删除`debugger`目录，然后`shell`建了个新的，问题解决，感谢
```
shell@mx4pro:/data/local/tmp $ mkdir debugger
mkdir debugger
shell@mx4pro:/data/local/tmp $ ls -l
ls -l
drwxrwxrwx shell    shell             2017-12-31 15:01 debugger
-rw------- root     root        85612 2017-12-31 14:29 jump.720.png
-rw-rw-r-- shell    shell       94567 2017-12-31 14:30 jump.png
-rwxrwxrwx shell    shell     2662585 2017-12-31 13:26 youjumpijump
shell@mx4pro:/data/local/tmp $ ./youjumpijump
./youjumpijump
input jump ratio (recommend 2.04):2.04
2017/12/31 07:02:39 now jump ratio is 2.040000
2017/12/31 07:02:42 from:[224 694] to:[526 524] press:706ms
2017/12/31 07:02:48 from:[204 704] to:[532 523] press:764ms
2017/12/31 07:02:56 from:[232 692] to:[508 536] press:646ms
2017/12/31 07:03:08 from:[285 663] to:[455 567] press:398ms
```

**Comment by faceair** [comment]
👍
