### ISSUE TITLE
the program has crashed

### ISSUE THREAD

**Issue by WonderLand33** [faceair/youjumpijump#38]
```
127|tiffany:/ $ cd /data/local/tmp/ && chmod 775 ./youjumpijump-android || true && ./youjumpijump-android
input jump ratio (recommend 2.04):1.8
2017/12/31 16:33:56 now jump ratio is 1.800000
2017/12/31 16:33:58 can't find the starting point，please export the debugger directory
tiffany:/data/local/tmp $ cd /data/local/tmp/ && chmod 775 ./youjumpijump-android || true && ./youjumpijump-android
input jump ratio (recommend 2.04):1.7
2017/12/31 16:34:15 now jump ratio is 1.700000
2017/12/31 16:34:18 from:[224 734] to:[526 566] press:587ms
2017/12/31 16:34:18 signal: killed: goroutine 1 [running]:
runtime/debug.Stack(0x10939e4c, 0x2333e0, 0x109bf1b0)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0x80
main.main.func1()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/android/main.go:21 +0x40
panic(0x2333e0, 0x109bf1b0)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x204
main.main()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/android/main.go:66 +0x534
the program has crashed, press any key to exit
```

**Comment by zhengmin4516** [comment]
我刚开始也这样，红米5，后来好像是打开了模拟点击就好了

**Comment by WonderLand33** [comment]
@zhengmin4516 没找到「模拟触摸」这一项

**Comment by zhengmin4516** [comment]
仔细看看，选项名有可能不叫模拟触摸，下面的小文字会介绍到是模拟点击

**Comment by Krisloveless** [comment]
打开USB debugging(Security settings)这个选项

**Comment by faceair** [comment]
没有更新的话 issue 先关了
