### ISSUE TITLE
IOS 10.3.3 运行崩溃

### ISSUE THREAD

**Issue by qfdk** [faceair/youjumpijump#40]
iOS 10.3.3 运行崩溃...

系统macOS 10.13

```
请输入 WebDriverAgentRunner 监听的 IP 和端口 (例如 192.168.9.94:8100):192.168.0.15:8100
请输入跳跃系数(推荐值 2，可适当调整):2
2017/12/31 22:31:52 现在跳跃系数是 2.000000
2017/12/31 22:31:52 illegal base64 data at input byte 2: goroutine 1 [running]:
runtime/debug.Stack(0xc42004baf8, 0x127ee60, 0xc42011a090)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0xa7
main.main.func1()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/ios/main.go:28 +0x73
panic(0x127ee60, 0xc42011a090)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
main.main()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/ios/main.go:68 +0xfab
程序已崩溃，按任意键退出
```
<img width="943" alt="snipaste_2017-12-31_22-32-18" src="https://user-images.githubusercontent.com/2404478/34464331-97b7bbd4-ee7a-11e7-9e2f-15e25d76bd08.png">

Xcode 对应的log

```
2017-12-31 22:31:20.510457+0100 WebDriverAgentRunner-Runner[8836:2354501] Enqueue Failure: Application local.pid.8466 is not running /Users/qfdk/Github/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
2017-12-31 22:31:20.513144+0100 WebDriverAgentRunner-Runner[8836:2354501] *** Assertion failure in -[XCUIScreen _screenshotDataForQuality:rect:error:], /Library/Caches/com.apple.xbs/Sources/XCTest_iOS/XCTest-13764/Sources/UITesting/XCUIScreen.m:230
2017-12-31 22:31:40.008062+0100 WebDriverAgentRunner-Runner[8836:2354501] *** Assertion failure in +[FBApplication fb_activeApplication], /Users/qfdk/Github/WebDriverAgent/WebDriverAgentLib/FBApplication.m:43
2017-12-31 22:31:42.791693+0100 WebDriverAgentRunner-Runner[8836:2354501] Continuing to run tests in the background with task ID 5
    t =   578.05s Find the Application "local.pid.8466" 0x1742b0260
2017-12-31 22:31:52.871054+0100 WebDriverAgentRunner-Runner[8836:2354501] Enqueue Failure: Application local.pid.8466 is not running /Users/qfdk/Github/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
    t =   578.06s Find the Application "local.pid.8466" 0x1742b0260
2017-12-31 22:31:52.876728+0100 WebDriverAgentRunner-Runner[8836:2354501] Enqueue Failure: Application local.pid.8466 is not running /Users/qfdk/Github/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
2017-12-31 22:31:52.879454+0100 WebDriverAgentRunner-Runner[8836:2354501] *** Assertion failure in -[XCUIScreen _screenshotDataForQuality:rect:error:], /Library/Caches/com.apple.xbs/Sources/XCTest_iOS/XCTest-13764/Sources/UITesting/XCUIScreen.m:230
```
web界面已经可以连接了... 但是 似乎没法运行. 崩溃也没有更详细的信息.

**Comment by qfdk** [comment]
知道怎么回事儿了... 先要关闭微信.. 要不然找不到句柄..  但是好奇怪.. bon
新年快乐 :)
