### ISSUE TITLE
三星 note4获取截图失败

### ISSUE THREAD

**Issue by mokamoe** [faceair/youjumpijump#44]
./youjumpijump-android: 1 file pushed. 4.1 MB/s (5445719 bytes in 1.252s)
shell@trhplte:/ $ su
root@trhplte:/ # cd /data/local/tmp
root@trhplte:/data/local/tmp # chmod 775 ./youjumpijump-android || true
root@trhplte:/data/local/tmp # ./youjumpijump-android
input jump ratio (recommend 2.04):2.04
2018/01/01 06:23:45 now jump ratio is 2.040000
2018/01/01 06:23:45 screenshot failed: goroutine 1 [running]:
runtime/debug.Stack(0x11f37df4, 0x207178, 0x26fca0)
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0x80
main.main.func1()
        /Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/android/
main.go:21 +0x40
panic(0x207178, 0x26fca0)
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x204
main.main()
        /Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/android/
main.go:49 +0x7e4
the program has crashed, press any key to exit

**Comment by faceair** [comment]
不太清楚原因，后来有弄好么？

**Comment by mokamoe** [comment]
没有任何改变。。。重试了几次。。

**Comment by faceair** [comment]
目前略改了一下截图，不会直接落盘，欢迎再次尝试一下
