### ISSUE TITLE
WebDriverAgentRunner 端口连接不上

### ISSUE THREAD

**Issue by luchaoqun123** [faceair/youjumpijump#71]
请输入 WebDriverAgentRunner 监听的 IP 和端口 (例如 192.168.9.94:8100):172.29.39.159:8100
请输入跳跃系数(推荐值 2，可适当调整):2
2018/01/02 15:56:01 现在跳跃系数是 2.000000
2018/01/02 15:56:02 Get http://172.29.39.159:8100/screenshot: dial tcp 172.29.39.159:8100: getsockopt: connection refused: goroutine 1 [running]:
runtime/debug.Stack(0xc42004baf8, 0x128f740, 0xc420079080)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0xa7
main.main.func1()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/ios/main.go:28 +0x73
panic(0x128f740, 0xc420079080)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
main.main()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/ios/main.go:57 +0xfcb
程序已崩溃，按任意键退出

**Comment by faceair** [comment]
用浏览器看 http://172.29.39.159:8100/status 看能否访问，不能的话可能是 wda 相关的设置问题。那份教程里好像有描述这种情况。

**Comment by recoyang** [comment]
我也遇到同样的问题，解决了吗，我试了iproxy 还是不行

**Comment by dangerlds** [comment]
同样的问题，求助

**Comment by jerardq** [comment]
我用iproxy解决这个问题的，用了iproxy要改成127.0.0.1:8100

**Comment by recoyang** [comment]
@jerardq 请问具体命令是？

**Comment by draft-jay** [comment]
iPhone SE ( iOS 11.2.1 )，WDA运行之后，在Mac浏览器 http://192.168.3.157:8100/status 打不开，一直在loading。使用`iproxy 8100 8100`后一直在`waiting for connection`,此时也是打不开那个地址的

**Comment by wanhmr** [comment]
用了 iproxy 就可以使用 http://localhost:8100/status

例如：iproxy 8100 8100
  
那么手机的端口已经被映射到电脑上的 8100 端口了。

**Comment by wanhmr** [comment]
@draft-jay 你使用  http://localhost:8100/status 试一下

**Comment by draft-jay** [comment]
@wanhmr 可以了
  大致步骤是：

1. 启动WDA
2. `iproxy 8100 8100`
3. 浏览器打开`http://localhost:8100/status` 有数据
4. `chmod 775 ./youjumpijump-ios && ./youjumpijump-ios` （这里的端口是`localhost:8100`）
