### ISSUE TITLE
Mi 5 设置完 jump ratio => the program has crashed, press any key to exit

### ISSUE THREAD

**Issue by JohnsonCaii** [faceair/youjumpijump#73]
![image](https://user-images.githubusercontent.com/23228405/34483670-fbdb4780-effa-11e7-89c5-b79130b18277.png)

```
2018/01/02 12:20:01 now jump ratio is 2.040000
2018/01/02 12:20:03 from:[238 728] to:[526 566] press:674ms
2018/01/02 12:20:03 signal: killed: goroutine 1 [running]:
runtime/debug.Stack(0x12378e4c, 0x2333e0, 0x10ab9160)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0x80
main.main.func1()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/android/main.go:21 +0x40
panic(0x2333e0, 0x10ab9160)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x204
main.main()
	/Users/faceair/Developer/Go/src/github.com/faceair/youjumpijump/android/main.go:66 +0x534

```

**Comment by faceair** [comment]
开发者选项中的相关安全设置打开了吗？

**Comment by JohnsonCaii** [comment]
忘记打开一部分手机的设置了，问题已解决！
